### ISSUE TITLE
HFR Data Access notebooks

### ISSUE THREAD

**Issue by jbosch-noaa** [jbosch-noaa/HFR_DataAccess_Evaluation#1]
@ocefpaf - Check out my very first repo!  I have 2 notebooks posted in this repo.  The first one runs the compliance checker on HFR data available on both the Scripps and the NDBC THREDDS.  

https://github.com/jbosch-noaa/HFR_DataAccess_Evaluation/blob/master/CC_NDBC_SIO_HFRdata.ipynb

The second notebook is where I access data on each of those servers using siphon.  I'm still working on that one. I just loaded it up to show you and Derrick.  

https://github.com/jbosch-noaa/HFR_DataAccess_Evaluation/blob/master/SIPHON_NCSS_HFR_DataAccess_v2.ipynb

For the compliance checker script I have one question.  It seems kinda silly for me to ask but how do I direct the output of the compliance checker to a text file from the python command line?

**Comment by ocefpaf** [comment]
Awesome! I like that they are to the point and easy to follow.

I believe that compliance checker has a rich display using HTML, right? Maybe we could try to use that to get a more "colorful" notebook. I will look into it soon.

**Comment by jbosch-noaa** [comment]
This notebook has been moved to ioos/notebooks_demos/notebooks/hfradar/
